[project]
name = "pyside-useful-widgets"
version = "0.1.0"
description = "Some useful pyside widgets that I don't want to write twice."
readme = "README.md"
authors = [
    { name = "KurisuNya", email = "cuizhu1216@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "pyside6>=6.10.3",
]

[build-system]
requires = ["uv_build>=0.11.11,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "matplotlib>=3.9.4",
]
